# TIPOS INT E FLOAT 
# INT = NUMERO INTEIRO 
# O TIPO INT REPRESENTA QUALQUER NUMERO 
# POSITIVO OU NEGATIVO INT SEM SINAL E CONSIDERADO POSITVO 

print(11)
print(-11)
print(0)

# FLOAT -> NUMERO COM PONTO FLUTUANTE 
# O TIPO FLOAT REPRESENTA QUALQUER NUMERO 
# POSITIVO OU NEGATIVO COM PONTO FLUTUANTE 
# FLOAT SEM SINAL E CONSIDERADO POSITIVO 

print(1.1, 10.2, 33.55, -1.2)

# A FUNCAO TYPE MOSTRA O TIPO EM PYTHON

print(type('Ola mundo'), type(2.2), type(2))
